update

diff --git a/common_mani_sake/tasks-git.yaml b/common_mani_sake/tasks-git.yaml
--- a/common_mani_sake/tasks-git.yaml
+++ b/common_mani_sake/tasks-git.yaml
@@ -1,10 +1,33 @@
 tasks:
+  g-cr:
+    desc: Create remote upstream
+    tags: [ git ]
+    spec: multi_repo
+    theme: multi_repo
+    env:
+      remote: upstream
+      brr:
+    cmd: |
+      f [ "$brr" = "" ]; then
+        echo "New branch from remote is required brr=new_branch"
+        exit 1
+      fi 
+      git remote add ${remote} ${MANI_PROJECT_URL}
+      git fetch ${remote} ${brr}
+      git checkout -b ${brr} remotes/${remote}/${brr}
+  g-sr:
+    desc: Git remote
+    tags: [ git ]
+    spec: multi_repo
+    cmd: |    
+      git remote
+
   g-fn:
     desc: Find git repositories
     target:
       all: false
     cmd: |     
-      find ${PROJECT_PATH} -type d -exec test -d {}/.git \; -prune -print
+      find ${MANI_PROJECT_PATH} -type d -exec test -d {}/.git \; -prune -print
 
   g-ft:
     desc: Fetch git
@@ -18,7 +41,7 @@ tasks:
     target: all
     env:
       igem: false
-    cmd: |
+    cmd: |      
       git status
 
   g-cst:
@@ -135,10 +158,17 @@ tasks:
     cmd: |
       if [ "$branch" = "" ]; then
         branch="${BRANCH_NAME}"
+      fi         
+      echo $(pwd)
+      echo "  push from ${branch}"
+      UNPUSHED=$(git log origin/$(git branch --show-current)..HEAD 2>/dev/null | wc -l)
+      if [ $UNPUSHED -gt 0 ]; then
+        git push origin $branch            
+        sleep 1        
+      else
+        echo "  ✅ Everything up-to-date"
       fi
-      echo "branch ph from LOCAL ${branch}"
-      git push origin $branch
-      sleep 2
+      echo " ** ** "
 
   g-send:
     desc: add commit and push git
diff --git a/common_mani_sake/tasks.yaml b/common_mani_sake/tasks.yaml
--- a/common_mani_sake/tasks.yaml
+++ b/common_mani_sake/tasks.yaml
@@ -1,4 +1,140 @@
 tasks:
+  t-omm:
+    desc: Odoo Mod Migrator
+    spec: multi_repo
+    theme: multi_repo
+    tags: [git]
+    env:
+      source:
+      target:
+      loglevel: "ERROR"
+      excdirs:
+      excmods:
+      excpatt:
+      patterns:
+      modules:
+    cmd: |
+      # odoo upgrade_code --addons-path ${MANI_PROJECT_PATH} --from ${source} --to ${target}
+      # sleep 1
+      if [ "$source" = "" ]; then
+          echo "Origin version is required: source"
+          exit 1
+      fi
+      if [ "$target" = "" ]; then
+          echo "Target version is required: target"
+          exit 1
+      fi
+      full_args=""
+      if [ "$excdirs" != "" ]; then
+        full_args="${full_args}--exc-dirs ${excdirs} "
+      fi
+      if [ "$excmods" != "" ]; then
+        full_args="${full_args}--exc-modules ${excmods} "
+      fi
+      if [ "$excpatt" != "" ]; then
+        full_args="${full_args}--exc-patterns ${excpatt} "
+      fi
+      if [ "$patterns" != "" ]; then
+        full_args="${full_args}--patterns ${patterns} "
+      fi
+      if [ "$modules" != "" ]; then
+        full_args="${full_args}--modules ${modules} "
+      fi
+      omig -d ${MANI_PROJECT_PATH} --init-version-name ${source} --target-version-name ${target} -nrmf -nc -npc --log-level ${loglevel} ${full_args}
+
+  t-omd:
+    desc: Odoo updacode Migrator
+    spec: multi_repo
+    theme: multi_repo
+    tags: [git]
+    env:
+      source:
+      target:
+      loglevel: "ERROR"
+      excdirs:
+      excmods:
+      excpatt:
+      patterns:
+      modules:
+    cmd: |      
+      # sleep 1
+      if [ "$source" = "" ]; then
+          echo "Origin version is required: source"
+          exit 1
+      fi
+      if [ "$target" = "" ]; then
+          echo "Target version is required: target"
+          exit 1
+      fi
+      full_args=""
+      if [ "$excdirs" != "" ]; then
+        full_args="${full_args}--exc-dirs ${excdirs} "
+      fi
+      if [ "$excmods" != "" ]; then
+        full_args="${full_args}--exc-modules ${excmods} "
+      fi
+      if [ "$excpatt" != "" ]; then
+        full_args="${full_args}--exc-patterns ${excpatt} "
+      fi
+      if [ "$patterns" != "" ]; then
+        full_args="${full_args}--patterns ${patterns} "
+      fi
+      if [ "$modules" != "" ]; then
+        full_args="${full_args}--modules ${modules} "
+      fi
+      odoo --addons-path=${MANI_PROJECT_PATH} upgrade_code --from ${source} --to ${target}
+
+  t-xom:
+    desc: Migration Odoo
+    spec: multi_repo
+    theme: multi_repo
+    tags: [git]
+    env:
+      source:
+      target:
+      loglevel: "ERROR"
+      excdirs:
+      excmods:
+      excpatt:
+      patterns:
+      modules:
+    cmd: |
+      if [ "$source" = "" ]; then
+          echo "Origin version is required: source"
+          exit 1
+      fi
+      if [ "$target" = "" ]; then
+          echo "Target version is required: target"
+          exit 1
+      fi
+      full_args=""
+      if [ "$excdirs" != "" ]; then
+        full_args="${full_args}--exc-dirs ${excdirs} "
+      fi
+      if [ "$excmods" != "" ]; then
+        full_args="${full_args}--exc-modules ${excmods} "
+      fi
+      if [ "$excpatt" != "" ]; then
+        full_args="${full_args}--exc-patterns ${excpatt} "
+      fi
+      if [ "$patterns" != "" ]; then
+        full_args="${full_args}--patterns ${patterns} "
+      fi
+      if [ "$modules" != "" ]; then
+        full_args="${full_args}--modules ${modules} "
+      fi
+      omig -d ${MANI_PROJECT_PATH} --init-version-name ${source} --target-version-name ${target} -nrmf -nc -npc --log-level ${loglevel} ${full_args}
+
+  t-cnv:
+    desc: Upgrade Odoo
+    spec: multi_repo
+    theme: multi_repo
+    env:
+      source: 14.0
+      target: 17.0
+    cmd: |
+      odoo upgrade_code --addons-path ${MANI_PROJECT_PATH} --from ${source} --to ${target}
+      sleep 2
 
   c-home:
     name: Cleanup home
